name: Wheels

on: [push, pull_request]

jobs:
  wheels:
    name: Build wheels on ${{ matrix.os }} ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-2019
            cmake_generator: "Visual Studio 16 2019"
            cmake_generator_platform: "x64"
            arch: AMD64
          - os: windows-2019
            cmake_generator: "Visual Studio 16 2019"
            cmake_generator_platform: "Win32"
            arch: x86
          - os: ubuntu-20.04
            arch: x86_64
          - os: ubuntu-20.04
            arch: aarch64
          - os: ubuntu-20.04
            arch: i686
          # macos-latest runs on arm64 architecture and cibuildwheel cross
          # compiling for x86_64 fails
          - os: macos-13
            arch: x86_64
          - os: macos-latest
            arch: arm64

    steps:
      - uses: actions/checkout@v2

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - uses: docker/setup-qemu-action@v1
        if: ${{ matrix.arch == 'aarch64' }}
        name: Set up QEMU

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel

      - name: Build wheels
        env:
          CIBW_ENVIRONMENT_WINDOWS: >
            CMAKE_GENERATOR="${{ matrix.cmake_generator }}"
            CMAKE_GENERATOR_PLATFORM="${{ matrix.cmake_generator_platform }}"
          CIBW_SKIP: pp* *-musllinux_* cp313-* cp39-*
          CIBW_ARCHS: ${{ matrix.arch }}
        run: |
            python -m cibuildwheel --output-dir wheelhouse python/

      - uses: actions/upload-artifact@v4
        with:
          name: wheel-${{ matrix.os }}-${{ matrix.arch }}
          path: ./wheelhouse/*.whl

  publish:
    needs: wheels
    name: Publish wheels to PyPI
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v4

      - name: Publish wheels to PyPI

        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
          packages_dir: artifact
